version: '3.8'

services:
  # Standard PostgreSQL for local development (fallback when Neon Local doesn't work)
  postgres:
    image: postgres:15-alpine
    container_name: acquisitions-postgres-local
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: neondb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Initialize the database if needed
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    networks:
      - acquisitions-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d neondb"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: acquisitions-app-local
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/neondb
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - ARCJET_KEY=${ARCJET_KEY}
    volumes:
      # Mount source code for hot reload in development
      - ./src:/app/src:ro
      - ./package.json:/app/package.json:ro
      # Node modules volume to avoid conflicts
      - node_modules:/app/node_modules
      # Logs directory for development
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - acquisitions-network
    develop:
      # Enable hot reload for development
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: ./package.json

volumes:
  node_modules:
  postgres_data:

networks:
  acquisitions-network:
    driver: bridge