services:
  # Application service for production
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: acquisitions-app-prod
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}
      - LOG_LEVEL=${LOG_LEVEL:-warn}
      - ARCJET_KEY=${ARCJET_KEY}
    restart: unless-stopped
    networks:
      - acquisitions-network
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "wget --no-verbose --tries=1 --spider --user-agent='Docker-Health-Check' http://localhost:3000/health || wget --no-verbose --tries=1 --spider --user-agent='Mozilla/5.0 (Docker Health Check)' http://localhost:3000/ || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Security and resource limits
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
      - /app/logs:noexec,nosuid,size=50m
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M

  # Optional: Reverse proxy with nginx for production
  nginx:
    image: nginx:alpine
    container_name: acquisitions-nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      app:
        condition: service_healthy
    networks:
      - acquisitions-network
    restart: unless-stopped
    profiles:
      # Use profile to make nginx optional
      - with-nginx

networks:
  acquisitions-network:
    driver: bridge
